src/anonce/urls.py
from django.urls import  path
from .views import anonce_list_view

app_name="anonce"

urlpatterns = [
    path('',anonce_list_view,name="anonce-view")
]

src/bffbook/urls.py
 
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from .views import home_view
from .views import Announcement_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , home_view,name ='home-view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls',namespace='profiles')),
    path('posts/', include('posts.urls',namespace='posts')),
    path('anonce/', include('anonce.urls',namespace='anonce')),
    


]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view,like_unlike_post, PostDeleteView, PostUpdateView

 

app_name='posts'

urlpatterns = [
    path('',post_comment_create_and_list_view,name="main-post-view"),
    path('Liked/',like_unlike_post,name="like-post-view"),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post_update'), 
    
]

src/profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, 
    invites_received_view,
     profile_list_view, 
     invite_profile_list_view,
     ProfileListView,
     send_invatation,
     remove_from_friends,
     accept_invatation,
     reject_invatation,
     ProfileDetailView,
     )

app_name ='profiles'

urlpatterns = [ 
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view,name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),

    path('to-invite/', invite_profile_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation , name='send-invite'),
    path('remove-friend/', remove_from_friends , name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/',accept_invatation,name="accept-invite"),
    path('my-invites/reject/',reject_invatation,name="reject-invite"),
    


    

] 
 

src/templates/main/home.html
{% extends 'base.html' %}
{% block title %}

{% endblock title %}
{% block content %}
<style type="text/css">

  .hidden.menu {
    display: none;
  }

  .masthead.segment {
    min-height: 700px;
    padding: 1em 0em;
  }
  .masthead .logo.item img {
    margin-right: 1em;
  }
  .masthead .ui.menu .ui.button {
    margin-left: 0.5em;
  }
  .masthead h1.ui.header {
    margin-top: 3em;
    margin-bottom: 0em;
    font-size: 4em;
    font-weight: normal;
  }
  .masthead h2 {
    font-size: 1.7em;
    font-weight: normal;
  }

  .ui.vertical.stripe {
    padding: 8em 0em;
  }
  .ui.vertical.stripe h3 {
    font-size: 2em;
  }
  .ui.vertical.stripe .button + h3,
  .ui.vertical.stripe p + h3 {
    margin-top: 3em;
  }
  .ui.vertical.stripe .floated.image {
    clear: both;
  }
  .ui.vertical.stripe p {
    font-size: 1.33em;
  }
  .ui.vertical.stripe .horizontal.divider {
    margin: 3em 0em;
  }

  .quote.stripe.segment {
    padding: 0em;
  }
  .quote.stripe.segment .grid .column {
    padding-top: 5em;
    padding-bottom: 5em;
  }

  .footer.segment {
    padding: 5em 0em;
  }

  .secondary.pointing.menu .toc.item {
    display: none;
  }

  @media only screen and (max-width: 700px) {
    .ui.fixed.menu {
      display: none !important;
    }
    .secondary.pointing.menu .item,
    .secondary.pointing.menu .menu {
      display: none;
    }
    .secondary.pointing.menu .toc.item {
      display: block;
    }
    .masthead.segment {
      min-height: 350px;
    }
    .masthead h1.ui.header {
      font-size: 2em;
      margin-top: 1.5em;
    }
    .masthead h2 {
      margin-top: 0.5em;
      font-size: 1.5em;
    }
  }


</style>

<script src="assets/library/jquery.min.js"></script>
<script src="../dist/components/visibility.js"></script>
<script src="../dist/components/sidebar.js"></script>
<script src="../dist/components/transition.js"></script>
<script>
$(document)
  .ready(function() {

    // fix menu when passed
    $('.masthead')
      .visibility({
        once: false,
        onBottomPassed: function() {
          $('.fixed.menu').transition('fade in');
        },
        onBottomPassedReverse: function() {
          $('.fixed.menu').transition('fade out');
        }
      })
    ;

    // create sidebar and attach to menu open
    $('.ui.sidebar')
      .sidebar('attach events', '.toc.item')
    ;

  })
;
</script>
</head>
<body>





<!-- Page Contents -->
<div class="pusher">
<div class="ui inverted vertical masthead center aligned segment">

  <div class="ui text container">
    <h1 class="ui inverted header">
      Imagine-a-Network
    </h1>
    <h2>In which you can communicate easily.</h2>
    <div class="ui huge primary button">Get Started <i class="right arrow icon"></i></div>
  </div>

</div>

<div class="ui vertical stripe segment">
  <div class="ui middle aligned stackable grid container">
    <div class="row">
      <div class="eight wide column">
        <h3 class="ui header">We Help Companies and Companions</h3>
        <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
        <h3 class="ui header">We Make Bananas That Can Dance</h3>
        <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
      </div>
      <div class="six wide right floated column">
        <img src="assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
      </div>
    </div>
    <div class="row">
      <div class="center aligned column">
        <a class="ui huge button">Check Them Out</a>
      </div>
    </div>
  </div>
</div>


<div class="ui vertical stripe quote segment">
  <div class="ui equal width stackable internally celled grid">
    <div class="center aligned row">
      <div class="column">
        <h3>"What a Company"</h3>
        <p>That is what they all say about us</p>
      </div>
      <div class="column">
        <h3>"I shouldn't have gone with their competitor."</h3>
        <p>
          <img src="assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
        </p>
      </div>
    </div>
  </div>
</div>

<div class="ui vertical stripe segment">
  <div class="ui text container">
    <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
    <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
    <a class="ui large button">Read More</a>
    <h4 class="ui horizontal header divider">
      <a href="#">Case Studies</a>
    </h4>
    <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
    <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
    <a class="ui large button">I'm Still Quite Interested</a>
  </div>
</div>


<div class="ui inverted vertical footer segment">
  <div class="ui container">
    <div class="ui stackable inverted divided equal height stackable grid">
      <div class="three wide column">
        <h4 class="ui inverted header">About</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Sitemap</a>
          <a href="#" class="item">Contact Us</a>
          <a href="#" class="item">Religious Ceremonies</a>
          <a href="#" class="item">Gazebo Plans</a>
        </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Services</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Banana Pre-Order</a>
          <a href="#" class="item">DNA FAQ</a>
          <a href="#" class="item">How To Access</a>
          <a href="#" class="item">Favorite X-Men</a>
        </div>
      </div>
      <div class="seven wide column">
        <h4 class="">Footer Header</h4>
        <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
      </div>
    </div>
  </div>
</div>
</div>



{% endblock content %}
{% block scripts %}
{% endblock scripts %}

src/templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'Announcement_view' as path_to_Announcement %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
{% url 'anonce:anonce-view' as path_to_anonce %}

<div class="ui inverted menu ">
    <div class="ui container">
      <a href="{{path_to_home}}"  class="{% if request.path == path_to_home %}active{% endif %} item">
          <h3>Engineers </h3>
      </a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_anonce}}" class="{% if request.path == path_to_anonce %}active{% endif %} item">
          Announcements
      </a>
      {% endif %}
      <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Board
    </a>
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <div class="item">
              <div class="ui floating dropdown icon button teal"> Friends
                  <i class="dropdown icon"></i>
                  <div class="menu">
                      <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                          All Profiles
                      </a>
                      <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                          Send Invites
                      </a>
                      <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                          Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                      </a>
                  </div>
               </div>
          </div>
               <div class="item">
                <form action="" method="GET">
                  {% csrf_token %}
                  <div class="ui action left icon input">
                  <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                  <i class="search icon"></i>
                  <button type='submit' class="ui button">Search</button>
                  </div>
              </form>
              </div>
          
              <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                  <img src={{picture.url}} class="ui avatar image">&nbsp;
                   {{ request.user }}
              </a>
  
              <a href="{% url 'account_logout' %}" class="ui item">
                  Logout
              </a>
          {% else %}
          <a href="{% url 'account_login' %}" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>